Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2020-12, with the labels that each got.

#36 fix: switch to new changelog image
  packs/C++/.lighthouse/jenkins-x/release.yaml
  packs/D/.lighthouse/jenkins-x/release.yaml
  packs/appserver/.lighthouse/jenkins-x/release.yaml
  packs/csharp/.lighthouse/jenkins-x/release.yaml
  packs/cwp/.lighthouse/jenkins-x/release.yaml
  packs/docker-helm/.lighthouse/jenkins-x/release.yaml
  packs/docker/.lighthouse/jenkins-x/release.yaml
  packs/go-mongodb/.lighthouse/jenkins-x/release.yaml
  packs/go-plugin/.lighthouse/jenkins-x/release.yaml
  packs/go/.lighthouse/jenkins-x/release.yaml
  packs/gradle/.lighthouse/jenkins-x/release.yaml
  packs/helm/.lighthouse/jenkins-x/release.yaml
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/release.yaml
  packs/javascript/.lighthouse/jenkins-x/release.yaml
  packs/jenkins/.lighthouse/jenkins-x/release.yaml
  packs/maven-java11/.lighthouse/jenkins-x/release.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml
  packs/maven/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-gpu-service/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-service/.lighthouse/jenkins-x/release.yaml
  packs/php/.lighthouse/jenkins-x/release.yaml
  packs/python/.lighthouse/jenkins-x/release.yaml
  packs/ruby/.lighthouse/jenkins-x/release.yaml
  packs/rust/.lighthouse/jenkins-x/release.yaml
  packs/scala/.lighthouse/jenkins-x/release.yaml
  packs/typescript/.lighthouse/jenkins-x/release.yaml
Labels: size/L

#29 fix: upgrade to nodejs 12
  packs/javascript/Dockerfile
  packs/typescript/Dockerfile
Labels: needs-ok-to-test, size/XS

#38 fix: use better replacement expression for chart version
  .lighthouse/jenkins-x/triggers.yaml
  packs/C++/.lighthouse/jenkins-x/release.yaml
  packs/D/.lighthouse/jenkins-x/release.yaml
  packs/appserver/.lighthouse/jenkins-x/release.yaml
  packs/csharp/.lighthouse/jenkins-x/release.yaml
  packs/cwp/.lighthouse/jenkins-x/release.yaml
  packs/docker-helm/.lighthouse/jenkins-x/release.yaml
  packs/docker/.lighthouse/jenkins-x/release.yaml
  packs/go-mongodb/.lighthouse/jenkins-x/release.yaml
  packs/go-plugin/.lighthouse/jenkins-x/release.yaml
  packs/go/.lighthouse/jenkins-x/release.yaml
  packs/gradle/.lighthouse/jenkins-x/pullrequest.yaml
  packs/gradle/.lighthouse/jenkins-x/release.yaml
  packs/helm/.lighthouse/jenkins-x/release.yaml
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/pullrequest.yaml
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/release.yaml
  packs/javascript/.lighthouse/jenkins-x/pullrequest.yaml
  packs/javascript/.lighthouse/jenkins-x/release.yaml
  packs/jenkins/.lighthouse/jenkins-x/release.yaml
  packs/maven-java11/.lighthouse/jenkins-x/release.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml
  packs/maven/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-gpu-service/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-service/.lighthouse/jenkins-x/release.yaml
  packs/nop/.lighthouse/jenkins-x/pullrequest.yaml
  packs/nop/.lighthouse/jenkins-x/release.yaml
  packs/php/.lighthouse/jenkins-x/release.yaml
  packs/python/.lighthouse/jenkins-x/release.yaml
  packs/ruby/.lighthouse/jenkins-x/release.yaml
  packs/rust/.lighthouse/jenkins-x/release.yaml
  packs/scala/.lighthouse/jenkins-x/release.yaml
  packs/typescript/.lighthouse/jenkins-x/pullrequest.yaml
  packs/typescript/.lighthouse/jenkins-x/release.yaml
Labels: size/L

#39 fix: use better images for building python
  packs/python/.lighthouse/jenkins-x/pullrequest.yaml
  packs/python/.lighthouse/jenkins-x/release.yaml
Labels: size/XS

#40 fix: use correct pipeline for releases
  environment/.lighthouse/jenkins-x/release.yaml
Labels: size/S

#48 fix: use correct name for multi arch step
  packs/go-plugin-multiarch/.lighthouse/jenkins-x/release.yaml
Labels: size/XS

#42 fix(doc): update doc link
  README.md
Labels: needs-ok-to-test, size/XS

#52 fix: upgrade to version 3.1.9
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, updatebot

#56 fix: inverse steps order so the correct version and value are used in…
  packs/go-plugin-multiarch/.lighthouse/jenkins-x/release.yaml
  packs/go-plugin/.lighthouse/jenkins-x/release.yaml
Labels: needs-ok-to-test, size/M

#43 feat(doc): add custom pipeline catalog section
  README.md
Labels: needs-ok-to-test, size/S

#55 fix(git): use conventional commit message for releases
  packs/C++/.lighthouse/jenkins-x/release.yaml
  packs/C++/charts/Makefile
  packs/D/.lighthouse/jenkins-x/release.yaml
  packs/D/charts/Makefile
  packs/appserver/.lighthouse/jenkins-x/release.yaml
  packs/appserver/charts/Makefile
  packs/csharp/.lighthouse/jenkins-x/release.yaml
  packs/csharp/charts/Makefile
  packs/cwp/.lighthouse/jenkins-x/release.yaml
  packs/cwp/charts/Makefile
  packs/docker-helm/.lighthouse/jenkins-x/release.yaml
  packs/docker/.lighthouse/jenkins-x/release.yaml
  packs/go-mongodb/.lighthouse/jenkins-x/release.yaml
  packs/go-mongodb/charts/Makefile
  packs/go-plugin-multiarch/.lighthouse/jenkins-x/release.yaml
  packs/go-plugin/.lighthouse/jenkins-x/release.yaml
  packs/go/.lighthouse/jenkins-x/release.yaml
  packs/go/charts/Makefile
  packs/gradle/.lighthouse/jenkins-x/release.yaml
  packs/helm/.lighthouse/jenkins-x/release.yaml
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/release.yaml
  packs/javascript/.lighthouse/jenkins-x/release.yaml
  packs/jenkins/.lighthouse/jenkins-x/release.yaml
  packs/maven-java11/.lighthouse/jenkins-x/release.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml
  packs/maven/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-gpu-service/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-service/.lighthouse/jenkins-x/release.yaml
  packs/php/.lighthouse/jenkins-x/release.yaml
  packs/python/.lighthouse/jenkins-x/release.yaml
  packs/ruby/.lighthouse/jenkins-x/release.yaml
  packs/rust/.lighthouse/jenkins-x/release.yaml
  packs/scala/.lighthouse/jenkins-x/release.yaml
  packs/scala/charts/Makefile
  packs/typescript/.lighthouse/jenkins-x/release.yaml
  packs/typescript/charts/Makefile
Labels: needs-ok-to-test, size/M

#41 update gradle to jdk11
  packs/gradle/.lighthouse/jenkins-x/pullrequest.yaml
  packs/gradle/.lighthouse/jenkins-x/release.yaml
  packs/gradle/Dockerfile
Labels: needs-ok-to-test, size/S

#57 fix(git): add missing 'chore' for conventional commits
  packs/gradle/charts/Makefile
  packs/javascript-ui-nginx/charts/Makefile
  packs/javascript/charts/Makefile
  packs/maven-java11/charts/Makefile
  packs/maven-node-ruby/charts/Makefile
  packs/maven-quarkus/charts/Makefile
  packs/maven/charts/Makefile
  packs/ml-python-gpu-service/charts/Makefile
  packs/ml-python-gpu-training/charts/Makefile
  packs/ml-python-service/charts/Makefile
  packs/ml-python-training/charts/Makefile
  packs/php/charts/Makefile
  packs/python/charts/Makefile
  packs/ruby/charts/Makefile
  packs/rust/charts/Makefile
Labels: needs-ok-to-test, size/M

#84 fix: use better image for helm releases
  packs/go-plugin-multiarch/.lighthouse/jenkins-x/release.yaml
  packs/go-plugin/.lighthouse/jenkins-x/release.yaml
Labels: size/XS
