Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2020-10, with the labels that each got.

#5 fix: remove disabled steps
  .lighthouse/jenkins-x/ci.sh
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/tests/Makefile
  .lighthouse/jenkins-x/tests/go.mod
  .lighthouse/jenkins-x/tests/go.sum
  .lighthouse/jenkins-x/tests/main_test.go
  .lighthouse/jenkins-x/triggers.yaml
  packs/apps/.lighthouse/jenkins-x/release.yaml
  packs/appserver/.lighthouse/jenkins-x/pullrequest.yaml
  packs/cwp/.lighthouse/jenkins-x/pullrequest.yaml
  packs/dropwizard/.lighthouse/jenkins-x/pullrequest.yaml
  packs/go-cli/.lighthouse/jenkins-x/release.yaml
  packs/go-mongodb/.lighthouse/jenkins-x/release.yaml
  packs/go-plugin/.lighthouse/jenkins-x/release.yaml
  packs/go/.lighthouse/jenkins-x/release.yaml
  packs/helm/.lighthouse/jenkins-x/release.yaml
  packs/javascript/.lighthouse/jenkins-x/release.yaml
  packs/liberty/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-java11/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven/.lighthouse/jenkins-x/pullrequest.yaml
  packs/typescript/.lighthouse/jenkins-x/release.yaml
Labels: size/XXL

#7 fix: remove unnecessary step
  .lighthouse/jenkins-x/release.yaml
  environment/.lighthouse/jenkins-x/release.yaml
  packs/C++/.lighthouse/jenkins-x/release.yaml
  packs/D/.lighthouse/jenkins-x/release.yaml
  packs/apps/.lighthouse/jenkins-x/release.yaml
  packs/appserver/.lighthouse/jenkins-x/release.yaml
  packs/charts/.lighthouse/jenkins-x/release.yaml
  packs/csharp/.lighthouse/jenkins-x/release.yaml
  packs/custom-jenkins/.lighthouse/jenkins-x/release.yaml
  packs/cwp/.lighthouse/jenkins-x/release.yaml
  packs/docker-helm/.lighthouse/jenkins-x/release.yaml
  packs/docker/.lighthouse/jenkins-x/release.yaml
  packs/dropwizard/.lighthouse/jenkins-x/release.yaml
  packs/environment-gitops/.lighthouse/jenkins-x/release.yaml
  packs/environment-helmfile/.lighthouse/jenkins-x/release.yaml
  packs/environment/.lighthouse/jenkins-x/release.yaml
  packs/git/.lighthouse/jenkins-x/release.yaml
  packs/go-cli/.lighthouse/jenkins-x/release.yaml
  packs/go-mongodb/.lighthouse/jenkins-x/release.yaml
  packs/go-plugin/.lighthouse/jenkins-x/release.yaml
  packs/go/.lighthouse/jenkins-x/release.yaml
  packs/gradle/.lighthouse/jenkins-x/release.yaml
  packs/helm/.lighthouse/jenkins-x/release.yaml
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/release.yaml
  packs/javascript/.lighthouse/jenkins-x/release.yaml
  packs/jenkins/.lighthouse/jenkins-x/release.yaml
  packs/jenkinsfilerunner/.lighthouse/jenkins-x/release.yaml
  packs/liberty/.lighthouse/jenkins-x/release.yaml
  packs/maven-java11/.lighthouse/jenkins-x/release.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml
  packs/maven/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-gpu-service/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-service/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-training/.lighthouse/jenkins-x/release.yaml
  packs/nop/.lighthouse/jenkins-x/release.yaml
  packs/php/.lighthouse/jenkins-x/release.yaml
  packs/python/.lighthouse/jenkins-x/release.yaml
  packs/ruby/.lighthouse/jenkins-x/release.yaml
  packs/rust/.lighthouse/jenkins-x/release.yaml
  packs/scala/.lighthouse/jenkins-x/release.yaml
  packs/trigger-jenkins/.lighthouse/jenkins-x/release.yaml
  packs/typescript/.lighthouse/jenkins-x/release.yaml
Labels: size/XL

#8 feat: modified kaniko image back to kaniko project maintained image now ACR environment docker cred helper has been merged
  packs/C++/.lighthouse/jenkins-x/pullrequest.yaml
  packs/C++/.lighthouse/jenkins-x/release.yaml
  packs/D/.lighthouse/jenkins-x/pullrequest.yaml
  packs/D/.lighthouse/jenkins-x/release.yaml
  packs/appserver/.lighthouse/jenkins-x/pullrequest.yaml
  packs/appserver/.lighthouse/jenkins-x/release.yaml
  packs/csharp/.lighthouse/jenkins-x/pullrequest.yaml
  packs/csharp/.lighthouse/jenkins-x/release.yaml
  packs/cwp/.lighthouse/jenkins-x/pullrequest.yaml
  packs/cwp/.lighthouse/jenkins-x/release.yaml
  packs/docker-helm/.lighthouse/jenkins-x/pullrequest.yaml
  packs/docker-helm/.lighthouse/jenkins-x/release.yaml
  packs/docker/.lighthouse/jenkins-x/pullrequest.yaml
  packs/docker/.lighthouse/jenkins-x/release.yaml
  packs/dropwizard/.lighthouse/jenkins-x/pullrequest.yaml
  packs/dropwizard/.lighthouse/jenkins-x/release.yaml
  packs/go-cli/.lighthouse/jenkins-x/pullrequest.yaml
  packs/go-cli/.lighthouse/jenkins-x/release.yaml
  packs/go-mongodb/.lighthouse/jenkins-x/pullrequest.yaml
  packs/go-mongodb/.lighthouse/jenkins-x/release.yaml
  packs/go-plugin/.lighthouse/jenkins-x/pullrequest.yaml
  packs/go-plugin/.lighthouse/jenkins-x/release.yaml
  packs/go/.lighthouse/jenkins-x/pullrequest.yaml
  packs/go/.lighthouse/jenkins-x/release.yaml
  packs/gradle/.lighthouse/jenkins-x/pullrequest.yaml
  packs/gradle/.lighthouse/jenkins-x/release.yaml
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/pullrequest.yaml
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/release.yaml
  packs/javascript/.lighthouse/jenkins-x/pullrequest.yaml
  packs/javascript/.lighthouse/jenkins-x/release.yaml
  packs/jenkins/.lighthouse/jenkins-x/pullrequest.yaml
  packs/jenkins/.lighthouse/jenkins-x/release.yaml
  packs/liberty/.lighthouse/jenkins-x/pullrequest.yaml
  packs/liberty/.lighthouse/jenkins-x/release.yaml
  packs/maven-java11/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-java11/.lighthouse/jenkins-x/release.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml
  packs/maven/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-gpu-service/.lighthouse/jenkins-x/pullrequest.yaml
  packs/ml-python-gpu-service/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-service/.lighthouse/jenkins-x/pullrequest.yaml
  packs/ml-python-service/.lighthouse/jenkins-x/release.yaml
  packs/php/.lighthouse/jenkins-x/pullrequest.yaml
  packs/php/.lighthouse/jenkins-x/release.yaml
  packs/python/.lighthouse/jenkins-x/pullrequest.yaml
  packs/python/.lighthouse/jenkins-x/release.yaml
  packs/ruby/.lighthouse/jenkins-x/pullrequest.yaml
  packs/ruby/.lighthouse/jenkins-x/release.yaml
  packs/rust/.lighthouse/jenkins-x/pullrequest.yaml
  packs/rust/.lighthouse/jenkins-x/release.yaml
  packs/scala/.lighthouse/jenkins-x/pullrequest.yaml
  packs/scala/.lighthouse/jenkins-x/release.yaml
  packs/typescript/.lighthouse/jenkins-x/pullrequest.yaml
  packs/typescript/.lighthouse/jenkins-x/release.yaml
Labels: lgtm, needs-ok-to-test, size/L

#10 fix: add a spike of reusable git clone tasks
  tasks/git-clone/git-clone-pr.yaml
  tasks/git-clone/git-clone.yaml
Labels: size/M
