Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2021-03, with the labels that each got.

#451 Adding default name to container port inside a Deployment
  helm/charts/templates/deployment.yaml
Labels: size/XS

#444 feat: added in optional env vars to environment pr pipeline that are populated by terraform or as part of cluster pre-reqs
  environment/.lighthouse/jenkins-x/pullrequest.yaml
Labels: needs-ok-to-test, size/XS

#466 fix: use consistent commands for maven PRs
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven/pullrequest.yaml
Labels: size/S

#463 fix: use 80 as internal port for th PHP buildpack
  packs/php/charts/values.yaml
Labels: needs-ok-to-test, size/XS

#468 fix: for flaky maven downloads in BDD tests
  packs/appserver/.lighthouse/jenkins-x/pullrequest.yaml
  packs/appserver/.lighthouse/jenkins-x/release.yaml
  packs/cwp/.lighthouse/jenkins-x/pullrequest.yaml
  packs/jenkins/.lighthouse/jenkins-x/pullrequest.yaml
  packs/jenkins/.lighthouse/jenkins-x/release.yaml
  packs/maven-java11/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-java11/.lighthouse/jenkins-x/release.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml
  packs/maven/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven/.lighthouse/jenkins-x/release.yaml
  tasks/appserver/pullrequest.yaml
  tasks/appserver/release.yaml
  tasks/cwp/pullrequest.yaml
  tasks/cwp/release.yaml
  tasks/jenkins/pullrequest.yaml
  tasks/jenkins/release.yaml
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/pullrequest.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/pullrequest.yaml
  tasks/maven/release.yaml
  tasks/scala/pullrequest.yaml
  tasks/scala/release.yaml
Labels: size/M

#480 fix: use the new push container registry variable
  tasks/C++/pullrequest.yaml
  tasks/C++/release.yaml
  tasks/D/pullrequest.yaml
  tasks/D/release.yaml
  tasks/appserver/pullrequest.yaml
  tasks/appserver/release.yaml
  tasks/csharp/pullrequest.yaml
  tasks/csharp/release.yaml
  tasks/cwp/pullrequest.yaml
  tasks/cwp/release.yaml
  tasks/docker-helm/pullrequest.yaml
  tasks/docker-helm/release.yaml
  tasks/docker/pullrequest.yaml
  tasks/docker/release.yaml
  tasks/go-cli/pullrequest.yaml
  tasks/go-cli/release.yaml
  tasks/go-mongodb/pullrequest.yaml
  tasks/go-mongodb/release.yaml
  tasks/go/pullrequest.yaml
  tasks/go/release.yaml
  tasks/gradle/pullrequest.yaml
  tasks/gradle/release.yaml
  tasks/javascript-ui-nginx/pullrequest.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/pullrequest.yaml
  tasks/javascript/release.yaml
  tasks/jenkins/pullrequest.yaml
  tasks/jenkins/release.yaml
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/pullrequest.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/pullrequest.yaml
  tasks/maven/release.yaml
  tasks/ml-python-gpu-service/pullrequest.yaml
  tasks/ml-python-gpu-service/release.yaml
  tasks/ml-python-service/pullrequest.yaml
  tasks/ml-python-service/release.yaml
  tasks/php/pullrequest.yaml
  tasks/php/release.yaml
  tasks/python/pullrequest.yaml
  tasks/python/release.yaml
  tasks/ruby/pullrequest.yaml
  tasks/ruby/release.yaml
  tasks/rust/pullrequest.yaml
  tasks/rust/release.yaml
  tasks/scala/pullrequest.yaml
  tasks/scala/release.yaml
  tasks/typescript/pullrequest.yaml
  tasks/typescript/release.yaml
Labels: size/L

#506 fix: first spike of a flutter pipeline
  packs/flutter/.lighthouse/jenkins-x/pullrequest.yaml
  packs/flutter/.lighthouse/jenkins-x/release.yaml
  packs/flutter/.lighthouse/jenkins-x/triggers.yaml
  tasks/flutter/pullrequest.yaml
  tasks/flutter/release.yaml
Labels: size/L

#508 fix: upgrade environment pipelines
  environment/.lighthouse/jenkins-x/pullrequest.yaml
  environment/.lighthouse/jenkins-x/release.yaml
Labels: size/M
