Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2021-05, with the labels that each got.

#656 fix: upgrade the ML images
  tasks/ml-python-gpu-service/pullrequest.yaml
  tasks/ml-python-gpu-service/release.yaml
  tasks/ml-python-service/pullrequest.yaml
  tasks/ml-python-service/release.yaml
  tasks/ml-python-training/pullrequest.yaml
  tasks/ml-python-training/release.yaml
Labels: size/M

#672 fix: Fix `extensions/pipeline-catalog.yaml` filename in `README.md`
  README.md
Labels: needs-ok-to-test, size/XS

#685 fix: Set defaults for MLOps
  packs/ml-python-gpu-service/charts/values.yaml
  packs/ml-python-gpu-training/charts/values.yaml
  packs/ml-python-service/charts/values.yaml
  packs/ml-python-training/charts/values.yaml
  tasks/ml-python-training/release.yaml
Labels: size/M

#695 fix: Realign step name with task definition
  packs/ml-python-service/.lighthouse/jenkins-x/release.yaml
Labels: size/XS

#734 fix: add missing http proxy env vars
  tasks/appserver/pullrequest.yaml
  tasks/appserver/release.yaml
  tasks/cwp/pullrequest.yaml
  tasks/cwp/release.yaml
  tasks/flutter/release.yaml
  tasks/git-clone/git-clone-pr.yaml
  tasks/git-clone/git-clone.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/pullrequest.yaml
  tasks/javascript/release.yaml
  tasks/jenkins/pullrequest.yaml
  tasks/jenkins/release.yaml
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/pullrequest.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/pullrequest.yaml
  tasks/maven/release.yaml
  tasks/scala/pullrequest.yaml
  tasks/scala/release.yaml
  tasks/typescript/pullrequest.yaml
  tasks/typescript/release.yaml
Labels: size/M

#731 feat: Add GPU support
  packs/ml-python-gpu-training/.lighthouse/jenkins-x/pullrequest.yaml
  packs/ml-python-gpu-training/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-gpu-training/.lighthouse/jenkins-x/triggers.yaml
  tasks/ml-python-gpu-training/pullrequest.yaml
  tasks/ml-python-gpu-training/release.yaml
Labels: size/L

#716 Maintain branch name semantics in git clone
  tasks/git-clone/git-clone-pr.yaml
  tasks/git-clone/git-clone.yaml
Labels: needs-ok-to-test, size/S

#740 Revert "chore(deps): upgrade jenkins-x/jx3-pipeline-catalog to version 2.4.5"
  packs/git/.lighthouse/jenkins-x/release.yaml
  tasks/C++/release.yaml
  tasks/D/release.yaml
  tasks/apps/release.yaml
  tasks/appserver/release.yaml
  tasks/charts/release.yaml
  tasks/csharp/release.yaml
  tasks/custom-jenkins/release.yaml
  tasks/cwp/release.yaml
  tasks/docker-helm/release.yaml
  tasks/docker/release.yaml
  tasks/flutter/release.yaml
  tasks/go-cli/release.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
  tasks/go/release.yaml
  tasks/gradle/release.yaml
  tasks/helm/release.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/release.yaml
  tasks/jenkins/release.yaml
  tasks/jenkinsfilerunner/release.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/release.yaml
  tasks/ml-python-gpu-service/release.yaml
  tasks/ml-python-gpu-training/release.yaml
  tasks/ml-python-service/release.yaml
  tasks/ml-python-training/release.yaml
  tasks/nop/release.yaml
  tasks/php/release.yaml
  tasks/python/release.yaml
  tasks/ruby/release.yaml
  tasks/rust/release.yaml
  tasks/scala/release.yaml
  tasks/terraform/release.yaml
  tasks/typescript/release.yaml
Labels: size/M

#741 chore: move jx-release-version image from gcr to ghcr
  packs/git/.lighthouse/jenkins-x/release.yaml
  tasks/C++/release.yaml
  tasks/D/release.yaml
  tasks/apps/release.yaml
  tasks/appserver/release.yaml
  tasks/charts/release.yaml
  tasks/csharp/release.yaml
  tasks/custom-jenkins/release.yaml
  tasks/cwp/release.yaml
  tasks/docker-helm/release.yaml
  tasks/docker/release.yaml
  tasks/flutter/release.yaml
  tasks/go-cli/release.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
  tasks/go/release.yaml
  tasks/gradle/release.yaml
  tasks/helm/release.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/release.yaml
  tasks/jenkins/release.yaml
  tasks/jenkinsfilerunner/release.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/release.yaml
  tasks/ml-python-gpu-service/release.yaml
  tasks/ml-python-gpu-training/release.yaml
  tasks/ml-python-service/release.yaml
  tasks/ml-python-training/release.yaml
  tasks/nop/release.yaml
  tasks/php/release.yaml
  tasks/python/release.yaml
  tasks/ruby/release.yaml
  tasks/rust/release.yaml
  tasks/scala/release.yaml
  tasks/terraform/release.yaml
  tasks/typescript/release.yaml
Labels: size/M

#747 feat: add a cosign task
  tasks/cosign/README.md
  tasks/cosign/cosign.yaml
Labels: size/M

#753 feat: labels variabilisation allowing to add labels to deployed apps
  helm/charts/templates/canary.yaml
  helm/charts/templates/deployment.yaml
  helm/charts/templates/hpa.yaml
  helm/charts/templates/ingress.yaml
  helm/charts/templates/ksvc.yaml
  helm/charts/templates/service.yaml
  helm/charts/values.yaml
Labels: needs-ok-to-test, size/M
