Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2021-04, with the labels that each got.

#562 chore: add a prefix to the env release pipeline name
  environment/.lighthouse/jenkins-x/triggers.yaml
Labels: needs-ok-to-test, size/XS

#599 fix: upgrade to nicer yset command
  tasks/C++/release.yaml
  tasks/D/release.yaml
  tasks/appserver/release.yaml
  tasks/csharp/release.yaml
  tasks/cwp/release.yaml
  tasks/docker-helm/release.yaml
  tasks/docker/release.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
  tasks/go/release.yaml
  tasks/gradle/release.yaml
  tasks/helm/release.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/release.yaml
  tasks/jenkins/release.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/release.yaml
  tasks/ml-python-gpu-service/release.yaml
  tasks/ml-python-service/release.yaml
  tasks/php/release.yaml
  tasks/python/release.yaml
  tasks/ruby/release.yaml
  tasks/rust/release.yaml
  tasks/scala/release.yaml
  tasks/typescript/release.yaml
Labels: size/L

#628 fix: add optional npm config to PRs too
  tasks/javascript/pullrequest.yaml
Labels: size/S

#634 fix: add the PR environment variables
  tasks/C++/pullrequest.yaml
  tasks/D/pullrequest.yaml
  tasks/apps/pullrequest.yaml
  tasks/appserver/pullrequest.yaml
  tasks/charts/pullrequest.yaml
  tasks/csharp/pullrequest.yaml
  tasks/custom-jenkins/pullrequest.yaml
  tasks/cwp/pullrequest.yaml
  tasks/docker-helm/pullrequest.yaml
  tasks/docker/pullrequest.yaml
  tasks/flutter/pullrequest.yaml
  tasks/go-cli/pullrequest.yaml
  tasks/go-mongodb/pullrequest.yaml
  tasks/go-plugin-multiarch/pullrequest.yaml
  tasks/go-plugin/pullrequest.yaml
  tasks/go/pullrequest.yaml
  tasks/gradle/pullrequest.yaml
  tasks/helm/pullrequest.yaml
  tasks/javascript-ui-nginx/pullrequest.yaml
  tasks/javascript/pullrequest.yaml
  tasks/jenkins/pullrequest.yaml
  tasks/jenkinsfilerunner/pullrequest.yaml
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven-quarkus/pullrequest.yaml
  tasks/maven/pullrequest.yaml
  tasks/ml-python-gpu-service/pullrequest.yaml
  tasks/ml-python-service/pullrequest.yaml
  tasks/ml-python-training/pullrequest.yaml
  tasks/nop/pullrequest.yaml
  tasks/php/pullrequest.yaml
  tasks/python/pullrequest.yaml
  tasks/ruby/pullrequest.yaml
  tasks/rust/pullrequest.yaml
  tasks/scala/pullrequest.yaml
  tasks/terraform/pullrequest.yaml
  tasks/typescript/pullrequest.yaml
Labels: size/M
