Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2021-08, with the labels that each got.

#877 Maven-java14 and maven-java16 build packs
  README.md
  packs/maven-java14/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-java14/.lighthouse/jenkins-x/release.yaml
  packs/maven-java14/.lighthouse/jenkins-x/triggers.yaml
  packs/maven-java14/Dockerfile
  packs/maven-java14/charts/.helmignore
  packs/maven-java14/charts/Chart.yaml
  packs/maven-java14/charts/Kptfile
  packs/maven-java14/charts/Makefile
  packs/maven-java14/charts/README.md
  packs/maven-java14/charts/templates/NOTES.txt
  packs/maven-java14/charts/templates/_helpers.tpl
  packs/maven-java14/charts/templates/canary.yaml
  packs/maven-java14/charts/templates/deployment.yaml
  packs/maven-java14/charts/templates/hpa.yaml
  packs/maven-java14/charts/templates/ingress.yaml
  packs/maven-java14/charts/templates/ksvc.yaml
  packs/maven-java14/charts/templates/sa.yaml
  packs/maven-java14/charts/templates/service.yaml
  packs/maven-java14/charts/values.yaml
  packs/maven-java14/preview/Kptfile
  packs/maven-java14/preview/helmfile.yaml
  packs/maven-java14/preview/values.yaml.gotmpl
  packs/maven-java16/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-java16/.lighthouse/jenkins-x/release.yaml
  packs/maven-java16/.lighthouse/jenkins-x/triggers.yaml
  packs/maven-java16/Dockerfile
  packs/maven-java16/charts/.helmignore
  packs/maven-java16/charts/Chart.yaml
  packs/maven-java16/charts/Kptfile
  packs/maven-java16/charts/Makefile
  packs/maven-java16/charts/README.md
  packs/maven-java16/charts/templates/NOTES.txt
  packs/maven-java16/charts/templates/_helpers.tpl
  packs/maven-java16/charts/templates/canary.yaml
  packs/maven-java16/charts/templates/deployment.yaml
  packs/maven-java16/charts/templates/hpa.yaml
  packs/maven-java16/charts/templates/ingress.yaml
  packs/maven-java16/charts/templates/ksvc.yaml
  packs/maven-java16/charts/templates/sa.yaml
  packs/maven-java16/charts/templates/service.yaml
  packs/maven-java16/charts/values.yaml
  packs/maven-java16/preview/Kptfile
  packs/maven-java16/preview/helmfile.yaml
  packs/maven-java16/preview/values.yaml.gotmpl
  tasks/maven-java14/pullrequest.yaml
  tasks/maven-java14/release.yaml
  tasks/maven-java16/pullrequest.yaml
  tasks/maven-java16/release.yaml
Labels: size/XXL, needs-ok-to-test, lgtm

#846 feat: create lookml pack and pipelines
  packs/lookml/.lighthouse/README.md
  packs/lookml/.lighthouse/jenkins-x/lint.yaml
  packs/lookml/.lighthouse/jenkins-x/pullrequest.yaml
  packs/lookml/.lighthouse/jenkins-x/release.yaml
  packs/lookml/.lighthouse/jenkins-x/triggers.yaml
  packs/lookml/charts/.helmignore
  packs/lookml/charts/Chart.yaml
  packs/lookml/charts/Kptfile
  packs/lookml/charts/Makefile
  packs/lookml/charts/README.md
  packs/lookml/charts/templates/NOTES.txt
  packs/lookml/charts/templates/_helpers.tpl
  packs/lookml/charts/templates/deploy-hook-job.yaml
  packs/lookml/charts/values.yaml
  tasks/lookml/lint.yaml
  tasks/lookml/pullrequest.yaml
  tasks/lookml/release.yaml
Labels: size/XL, needs-ok-to-test

#898 fix: drop up to 2 'regenerate' commits on merge conflict
  tasks/git-clone/git-clone-env-pr.yaml
Labels: lgtm, size/S, ok-to-test
