Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2021-02, with the labels that each got.

#302 chore: switch to jx-admin image
  environment/.lighthouse/jenkins-x/release.yaml
Labels: size/XS

#308 chore: switch to ghcr.io image for preview
  tasks/C++/pullrequest.yaml
  tasks/D/pullrequest.yaml
  tasks/appserver/pullrequest.yaml
  tasks/csharp/pullrequest.yaml
  tasks/cwp/pullrequest.yaml
  tasks/go-mongodb/pullrequest.yaml
  tasks/go/pullrequest.yaml
  tasks/gradle/pullrequest.yaml
  tasks/javascript-ui-nginx/pullrequest.yaml
  tasks/javascript/pullrequest.yaml
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven-quarkus/pullrequest.yaml
  tasks/maven/pullrequest.yaml
  tasks/ml-python-gpu-service/pullrequest.yaml
  tasks/ml-python-service/pullrequest.yaml
  tasks/php/pullrequest.yaml
  tasks/python/pullrequest.yaml
  tasks/ruby/pullrequest.yaml
  tasks/rust/pullrequest.yaml
  tasks/scala/pullrequest.yaml
  tasks/typescript/pullrequest.yaml
Labels: size/M

#322 chore: fix rust catalog
  tasks/rust/pullrequest.yaml
  tasks/rust/release.yaml
Labels: size/XS

#320 fix: use sh for jx-release-version
  packs/git/.lighthouse/jenkins-x/release.yaml
  tasks/C++/release.yaml
  tasks/D/release.yaml
  tasks/apps/release.yaml
  tasks/appserver/release.yaml
  tasks/charts/release.yaml
  tasks/csharp/release.yaml
  tasks/custom-jenkins/release.yaml
  tasks/cwp/release.yaml
  tasks/docker-helm/release.yaml
  tasks/docker/release.yaml
  tasks/go-cli/release.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
  tasks/go/release.yaml
  tasks/gradle/release.yaml
  tasks/helm/release.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/release.yaml
  tasks/jenkins/release.yaml
  tasks/jenkinsfilerunner/release.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/release.yaml
  tasks/ml-python-gpu-service/release.yaml
  tasks/ml-python-service/release.yaml
  tasks/ml-python-training/release.yaml
  tasks/nop/release.yaml
  tasks/php/release.yaml
  tasks/python/release.yaml
  tasks/ruby/release.yaml
  tasks/rust/release.yaml
  tasks/scala/release.yaml
  tasks/typescript/release.yaml
Labels: needs-ok-to-test, size/M

#325 chore: fix add reusable environment pipelines
  tasks/environment/pullrequest.yaml
  tasks/environment/release.yaml
Labels: size/M

#328 fix: improve rust catalog
  packs/rust/.lighthouse/jenkins-x/pullrequest.yaml
  packs/rust/.lighthouse/jenkins-x/release.yaml
  tasks/rust/pullrequest.yaml
  tasks/rust/release.yaml
Labels: size/M

#330 chore: avoid alpine image for now
  tasks/rust/pullrequest.yaml
  tasks/rust/release.yaml
Labels: size/XS

#333 chore: fix the rust image
  packs/rust/Dockerfile
Labels: size/XS

#339 fix: add an updatebot step
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/release.yaml
  tasks/updatebot/release.yaml
Labels: size/L

#340 fix: set the maven pom for releases
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/tests/go.sum
  .lighthouse/jenkins-x/tests/main_test.go
  tasks/C++/release.yaml
  tasks/D/release.yaml
  tasks/appserver/release.yaml
  tasks/csharp/release.yaml
  tasks/cwp/release.yaml
  tasks/docker-helm/release.yaml
  tasks/docker/release.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
  tasks/go/release.yaml
  tasks/gradle/release.yaml
  tasks/helm/release.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/release.yaml
  tasks/jenkins/release.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/release.yaml
  tasks/ml-python-gpu-service/release.yaml
  tasks/ml-python-service/release.yaml
  tasks/php/release.yaml
  tasks/python/release.yaml
  tasks/ruby/release.yaml
  tasks/rust/release.yaml
  tasks/scala/release.yaml
  tasks/typescript/release.yaml
Labels: size/L

#343 fix: use 'Always' as imagePullPolicy to avoid using old images if the PR build count is reseted
  packs/C++/preview/values.yaml.gotmpl
  packs/D/preview/values.yaml.gotmpl
  packs/appserver/preview/values.yaml.gotmpl
  packs/csharp/preview/values.yaml.gotmpl
  packs/cwp/preview/values.yaml.gotmpl
  packs/go-mongodb/preview/values.yaml.gotmpl
  packs/go/preview/values.yaml.gotmpl
  packs/gradle/preview/values.yaml.gotmpl
  packs/javascript-ui-nginx/preview/values.yaml.gotmpl
  packs/javascript/preview/values.yaml.gotmpl
  packs/maven-java11/preview/values.yaml.gotmpl
  packs/maven-node-ruby/preview/values.yaml.gotmpl
  packs/maven-quarkus/preview/values.yaml.gotmpl
  packs/maven/preview/values.yaml.gotmpl
  packs/ml-python-gpu-service/preview/values.yaml.gotmpl
  packs/ml-python-gpu-training/preview/values.yaml.gotmpl
  packs/ml-python-service/preview/values.yaml.gotmpl
  packs/ml-python-training/preview/values.yaml.gotmpl
  packs/php/preview/values.yaml.gotmpl
  packs/python/preview/values.yaml.gotmpl
  packs/ruby/preview/values.yaml.gotmpl
  packs/rust/preview/values.yaml.gotmpl
  packs/scala/preview/values.yaml.gotmpl
  packs/typescript/preview/values.yaml.gotmpl
Labels: needs-ok-to-test, size/S

#364 fix: add a verify pod chart
  helm/preview/helmfile.yaml
Labels: size/XS

#367 fix: latest preview yaml
  packs/C++/charts/Kptfile
  packs/C++/preview/Kptfile
  packs/D/charts/Kptfile
  packs/D/preview/Kptfile
  packs/appserver/charts/Kptfile
  packs/appserver/preview/Kptfile
  packs/csharp/charts/Kptfile
  packs/csharp/preview/Kptfile
  packs/cwp/charts/Kptfile
  packs/cwp/preview/Kptfile
  packs/go-mongodb/charts/Kptfile
  packs/go-mongodb/preview/Kptfile
  packs/go/charts/Kptfile
  packs/go/preview/Kptfile
  packs/go/preview/helmfile.yaml
  packs/gradle/charts/Kptfile
  packs/gradle/preview/Kptfile
  packs/javascript-ui-nginx/charts/Kptfile
  packs/javascript-ui-nginx/preview/Kptfile
  packs/javascript/charts/Kptfile
  packs/javascript/preview/Kptfile
  packs/maven-java11/charts/Kptfile
  packs/maven-java11/preview/Kptfile
  packs/maven-node-ruby/charts/Kptfile
  packs/maven-node-ruby/preview/Kptfile
  packs/maven-quarkus/charts/Kptfile
  packs/maven-quarkus/preview/Kptfile
  packs/maven/charts/Kptfile
  packs/maven/preview/Kptfile
  packs/ml-python-gpu-service/charts/Kptfile
  packs/ml-python-gpu-service/preview/Kptfile
  packs/ml-python-gpu-training/charts/Kptfile
  packs/ml-python-gpu-training/preview/Kptfile
  packs/ml-python-service/charts/Kptfile
  packs/ml-python-service/preview/Kptfile
  packs/ml-python-training/charts/Kptfile
  packs/ml-python-training/preview/Kptfile
  packs/php/charts/Kptfile
  packs/php/preview/Kptfile
  packs/python/charts/Kptfile
  packs/python/preview/Kptfile
  packs/ruby/charts/Kptfile
  packs/ruby/preview/Kptfile
  packs/rust/charts/Kptfile
  packs/rust/preview/Kptfile
  packs/scala/charts/Kptfile
  packs/scala/preview/Kptfile
  packs/typescript/charts/Kptfile
  packs/typescript/preview/Kptfile
Labels: size/M

#371 chore: do not change version for PRs
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven-quarkus/pullrequest.yaml
Labels: size/XS

#378 chore: use more concise preview URLs
  packs/C++/preview/values.yaml.gotmpl
  packs/D/preview/values.yaml.gotmpl
  packs/appserver/preview/values.yaml.gotmpl
  packs/csharp/preview/values.yaml.gotmpl
  packs/cwp/preview/values.yaml.gotmpl
  packs/go-mongodb/preview/values.yaml.gotmpl
  packs/go/preview/values.yaml.gotmpl
  packs/gradle/preview/values.yaml.gotmpl
  packs/javascript-ui-nginx/preview/values.yaml.gotmpl
  packs/javascript/preview/values.yaml.gotmpl
  packs/maven-java11/preview/values.yaml.gotmpl
  packs/maven-node-ruby/preview/values.yaml.gotmpl
  packs/maven-quarkus/preview/values.yaml.gotmpl
  packs/maven/preview/values.yaml.gotmpl
  packs/ml-python-gpu-service/preview/values.yaml.gotmpl
  packs/ml-python-gpu-training/preview/values.yaml.gotmpl
  packs/ml-python-service/preview/values.yaml.gotmpl
  packs/ml-python-training/preview/values.yaml.gotmpl
  packs/php/preview/values.yaml.gotmpl
  packs/python/preview/values.yaml.gotmpl
  packs/ruby/preview/values.yaml.gotmpl
  packs/rust/preview/values.yaml.gotmpl
  packs/scala/preview/values.yaml.gotmpl
  packs/typescript/preview/values.yaml.gotmpl
Labels: size/M

#379 chore: avoid old builder image
  tasks/go-cli/pullrequest.yaml
  tasks/go-mongodb/pullrequest.yaml
  tasks/go-mongodb/release.yaml
  tasks/go/pullrequest.yaml
  tasks/go/release.yaml
Labels: size/S

#396 fix: add maven retries to avoid mvn download failures
  packs/appserver/.lighthouse/jenkins-x/pullrequest.yaml
  packs/appserver/.lighthouse/jenkins-x/release.yaml
  packs/cwp/.lighthouse/jenkins-x/pullrequest.yaml
  packs/jenkins/.lighthouse/jenkins-x/pullrequest.yaml
  packs/jenkins/.lighthouse/jenkins-x/release.yaml
  packs/maven-java11/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-java11/.lighthouse/jenkins-x/release.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml
  packs/maven/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven/.lighthouse/jenkins-x/release.yaml
  tasks/appserver/pullrequest.yaml
  tasks/appserver/release.yaml
  tasks/cwp/pullrequest.yaml
  tasks/cwp/release.yaml
  tasks/jenkins/pullrequest.yaml
  tasks/jenkins/release.yaml
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/pullrequest.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/pullrequest.yaml
  tasks/maven/release.yaml
  tasks/scala/pullrequest.yaml
  tasks/scala/release.yaml
Labels: size/M

#397 chore: upgrade versions
  tasks/C++/release.yaml
  tasks/D/release.yaml
  tasks/apps/release.yaml
  tasks/appserver/release.yaml
  tasks/csharp/release.yaml
  tasks/cwp/release.yaml
  tasks/docker-helm/release.yaml
  tasks/docker/release.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
  tasks/go/release.yaml
  tasks/gradle/release.yaml
  tasks/helm/release.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/release.yaml
  tasks/jenkins/release.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/release.yaml
  tasks/ml-python-gpu-service/release.yaml
  tasks/ml-python-service/release.yaml
  tasks/php/release.yaml
  tasks/python/release.yaml
  tasks/ruby/release.yaml
  tasks/rust/release.yaml
  tasks/scala/release.yaml
  tasks/typescript/release.yaml
  tasks/updatebot/release.yaml
Labels: size/L

#398 chore: improve maven download retries
  packs/appserver/.lighthouse/jenkins-x/pullrequest.yaml
  packs/appserver/.lighthouse/jenkins-x/release.yaml
  packs/cwp/.lighthouse/jenkins-x/pullrequest.yaml
  packs/jenkins/.lighthouse/jenkins-x/pullrequest.yaml
  packs/jenkins/.lighthouse/jenkins-x/release.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml
  packs/maven/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven/.lighthouse/jenkins-x/release.yaml
  tasks/appserver/pullrequest.yaml
  tasks/appserver/release.yaml
  tasks/cwp/pullrequest.yaml
  tasks/cwp/release.yaml
  tasks/jenkins/pullrequest.yaml
  tasks/jenkins/release.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/pullrequest.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/pullrequest.yaml
  tasks/maven/release.yaml
  tasks/scala/pullrequest.yaml
  tasks/scala/release.yaml
Labels: size/L

#399 chore: fix maven env vars
  packs/maven-java11/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-java11/.lighthouse/jenkins-x/release.yaml
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-java11/release.yaml
Labels: size/S

#401 chore: add maven settings for PRs too
  tasks/cwp/release.yaml
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven-quarkus/pullrequest.yaml
  tasks/maven/pullrequest.yaml
  tasks/scala/pullrequest.yaml
  tasks/scala/release.yaml
Labels: size/M

#402 fix: add mvn settings for previews
  packs/maven-java11/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven/.lighthouse/jenkins-x/pullrequest.yaml
Labels: size/S

#438 fix: add more sophisticated logic for combining ingress annotations
  helm/charts/templates/ingress.yaml
Labels: size/S

#441 fix: the ingress template
  helm/charts/templates/ingress.yaml
  helm/charts/values.yaml
Labels: size/S
