Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2021-06, with the labels that each got.

#767 fix: Limits must be set for GPU utilisation
  tasks/ml-python-gpu-training/release.yaml
Labels: size/XS

#793 chore: use $DOCKERFILE_PATH everywhere
  tasks/C++/pullrequest.yaml
  tasks/C++/release.yaml
  tasks/D/pullrequest.yaml
  tasks/D/release.yaml
  tasks/appserver/pullrequest.yaml
  tasks/appserver/release.yaml
  tasks/csharp/pullrequest.yaml
  tasks/csharp/release.yaml
  tasks/cwp/pullrequest.yaml
  tasks/cwp/release.yaml
  tasks/docker-helm/pullrequest.yaml
  tasks/docker-helm/release.yaml
  tasks/docker/pullrequest.yaml
  tasks/docker/release.yaml
  tasks/go-cli/pullrequest.yaml
  tasks/go-cli/release.yaml
  tasks/go-mongodb/pullrequest.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
  tasks/go/pullrequest.yaml
  tasks/go/release.yaml
  tasks/gradle/pullrequest.yaml
  tasks/gradle/release.yaml
  tasks/javascript-ui-nginx/pullrequest.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/pullrequest.yaml
  tasks/javascript/release.yaml
  tasks/jenkins/pullrequest.yaml
  tasks/jenkins/release.yaml
  tasks/maven-java11/pullrequest.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/pullrequest.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/pullrequest.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/pullrequest.yaml
  tasks/maven/release.yaml
  tasks/ml-python-gpu-service/pullrequest.yaml
  tasks/ml-python-gpu-service/release.yaml
  tasks/ml-python-service/pullrequest.yaml
  tasks/ml-python-service/release.yaml
  tasks/php/pullrequest.yaml
  tasks/php/release.yaml
  tasks/python/pullrequest.yaml
  tasks/python/release.yaml
  tasks/ruby/pullrequest.yaml
  tasks/ruby/release.yaml
  tasks/rust/pullrequest.yaml
  tasks/rust/release.yaml
  tasks/scala/pullrequest.yaml
  tasks/scala/release.yaml
  tasks/typescript/pullrequest.yaml
  tasks/typescript/release.yaml
Labels: needs-ok-to-test, size/L

#810 fix: avoid the jx/ prefix on secret names
  environment-remote/.lighthouse/jenkins-x/pullrequest.yaml
  environment-remote/.lighthouse/jenkins-x/triggers.yaml
  helm/charts/templates/ingress.yaml
  packs/D/charts/Kptfile
  packs/D/preview/Kptfile
  packs/appserver/charts/Kptfile
  packs/appserver/preview/Kptfile
  packs/csharp/charts/Kptfile
  packs/csharp/preview/Kptfile
  packs/cwp/charts/Kptfile
  packs/cwp/preview/Kptfile
  packs/go-mongodb/charts/Kptfile
  packs/go-mongodb/preview/Kptfile
  packs/go/charts/Kptfile
  packs/go/preview/Kptfile
  packs/gradle/charts/Kptfile
  packs/gradle/preview/Kptfile
  packs/javascript-ui-nginx/charts/Kptfile
  packs/javascript-ui-nginx/preview/Kptfile
  packs/javascript/charts/Kptfile
  packs/javascript/preview/Kptfile
  packs/maven-java11/charts/Kptfile
  packs/maven-java11/preview/Kptfile
  packs/maven-node-ruby/charts/Kptfile
  packs/maven-node-ruby/preview/Kptfile
  packs/maven-quarkus/charts/Kptfile
  packs/maven-quarkus/preview/Kptfile
  packs/maven/charts/Kptfile
  packs/maven/preview/Kptfile
  packs/ml-python-gpu-service/charts/Kptfile
  packs/ml-python-gpu-service/preview/Kptfile
  packs/ml-python-gpu-training/charts/Kptfile
  packs/ml-python-gpu-training/preview/Kptfile
  packs/ml-python-service/charts/Kptfile
  packs/ml-python-service/preview/Kptfile
  packs/ml-python-training/charts/Kptfile
  packs/ml-python-training/preview/Kptfile
  packs/php/charts/Kptfile
  packs/php/preview/Kptfile
  packs/python/charts/Kptfile
  packs/python/preview/Kptfile
  packs/ruby/charts/Kptfile
  packs/ruby/preview/Kptfile
  packs/rust/charts/Kptfile
  packs/rust/preview/Kptfile
  packs/scala/charts/Kptfile
  packs/scala/preview/Kptfile
  packs/typescript/charts/Kptfile
  packs/typescript/preview/Kptfile
Labels: size/L

#818 chore: add quarkus-native pkg
  packs/maven-quarkus-native/.lighthouse/jenkins-x/pullrequest.yaml
  packs/maven-quarkus-native/.lighthouse/jenkins-x/release.yaml
  packs/maven-quarkus-native/.lighthouse/jenkins-x/triggers.yaml
  packs/maven-quarkus-native/Dockerfile
  packs/maven-quarkus-native/charts/.helmignore
  packs/maven-quarkus-native/charts/Chart.yaml
  packs/maven-quarkus-native/charts/Kptfile
  packs/maven-quarkus-native/charts/Makefile
  packs/maven-quarkus-native/charts/README.md
  packs/maven-quarkus-native/charts/templates/NOTES.txt
  packs/maven-quarkus-native/charts/templates/_helpers.tpl
  packs/maven-quarkus-native/charts/templates/canary.yaml
  packs/maven-quarkus-native/charts/templates/deployment.yaml
  packs/maven-quarkus-native/charts/templates/hpa.yaml
  packs/maven-quarkus-native/charts/templates/ingress.yaml
  packs/maven-quarkus-native/charts/templates/ksvc.yaml
  packs/maven-quarkus-native/charts/templates/sa.yaml
  packs/maven-quarkus-native/charts/templates/service.yaml
  packs/maven-quarkus-native/charts/values.yaml
  packs/maven-quarkus-native/preview/Kptfile
  packs/maven-quarkus-native/preview/helmfile.yaml
  packs/maven-quarkus-native/preview/values.yaml.gotmpl
  packs/maven-quarkus/Dockerfile
Labels: needs-ok-to-test, size/XL
