Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2021-01, with the labels that each got.

#151 fix: remove bad trigger/rerun configuration
  environment/.lighthouse/jenkins-x/triggers.yaml
  packs/C++/.lighthouse/jenkins-x/triggers.yaml
  packs/D/.lighthouse/jenkins-x/triggers.yaml
  packs/apps/.lighthouse/jenkins-x/triggers.yaml
  packs/appserver/.lighthouse/jenkins-x/triggers.yaml
  packs/charts/.lighthouse/jenkins-x/triggers.yaml
  packs/csharp/.lighthouse/jenkins-x/triggers.yaml
  packs/custom-jenkins/.lighthouse/jenkins-x/triggers.yaml
  packs/cwp/.lighthouse/jenkins-x/triggers.yaml
  packs/docker-helm/.lighthouse/jenkins-x/triggers.yaml
  packs/docker/.lighthouse/jenkins-x/triggers.yaml
  packs/go-cli/.lighthouse/jenkins-x/triggers.yaml
  packs/go-mongodb/.lighthouse/jenkins-x/triggers.yaml
  packs/go-plugin-multiarch/.lighthouse/jenkins-x/triggers.yaml
  packs/go-plugin/.lighthouse/jenkins-x/triggers.yaml
  packs/go/.lighthouse/jenkins-x/triggers.yaml
  packs/gradle/.lighthouse/jenkins-x/triggers.yaml
  packs/helm/.lighthouse/jenkins-x/triggers.yaml
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/triggers.yaml
  packs/javascript/.lighthouse/jenkins-x/triggers.yaml
  packs/jenkins/.lighthouse/jenkins-x/triggers.yaml
  packs/jenkinsfilerunner/.lighthouse/jenkins-x/triggers.yaml
  packs/maven-java11/.lighthouse/jenkins-x/triggers.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/triggers.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/triggers.yaml
  packs/maven/.lighthouse/jenkins-x/triggers.yaml
  packs/ml-python-gpu-service/.lighthouse/jenkins-x/triggers.yaml
  packs/ml-python-service/.lighthouse/jenkins-x/triggers.yaml
  packs/ml-python-training/.lighthouse/jenkins-x/triggers.yaml
  packs/nop/.lighthouse/jenkins-x/triggers.yaml
  packs/php/.lighthouse/jenkins-x/triggers.yaml
  packs/python/.lighthouse/jenkins-x/triggers.yaml
  packs/ruby/.lighthouse/jenkins-x/triggers.yaml
  packs/rust/.lighthouse/jenkins-x/triggers.yaml
  packs/scala/.lighthouse/jenkins-x/triggers.yaml
  packs/typescript/.lighthouse/jenkins-x/triggers.yaml
  tasks/lint/triggers.yaml
Labels: size/M

#156 fix: switch to --all mode for promote
  packs/C++/.lighthouse/jenkins-x/release.yaml
  packs/D/.lighthouse/jenkins-x/release.yaml
  packs/apps/.lighthouse/jenkins-x/release.yaml
  packs/appserver/.lighthouse/jenkins-x/release.yaml
  packs/csharp/.lighthouse/jenkins-x/release.yaml
  packs/cwp/.lighthouse/jenkins-x/release.yaml
  packs/docker-helm/.lighthouse/jenkins-x/release.yaml
  packs/go-mongodb/.lighthouse/jenkins-x/release.yaml
  packs/go/.lighthouse/jenkins-x/release.yaml
  packs/gradle/.lighthouse/jenkins-x/release.yaml
  packs/helm/.lighthouse/jenkins-x/release.yaml
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/release.yaml
  packs/javascript/.lighthouse/jenkins-x/release.yaml
  packs/maven-java11/.lighthouse/jenkins-x/release.yaml
  packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml
  packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml
  packs/maven/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-gpu-service/.lighthouse/jenkins-x/release.yaml
  packs/ml-python-service/.lighthouse/jenkins-x/release.yaml
  packs/php/.lighthouse/jenkins-x/release.yaml
  packs/python/.lighthouse/jenkins-x/release.yaml
  packs/ruby/.lighthouse/jenkins-x/release.yaml
  packs/rust/.lighthouse/jenkins-x/release.yaml
  packs/scala/.lighthouse/jenkins-x/release.yaml
  packs/typescript/.lighthouse/jenkins-x/release.yaml
Labels: size/M

#160 fix: switch to proper home dir for tekton
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/release.yaml
  packs/javascript/.lighthouse/jenkins-x/release.yaml
  packs/typescript/.lighthouse/jenkins-x/release.yaml
Labels: size/XS

#161 fix: use better npmrc mount
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/release.yaml
  packs/javascript/.lighthouse/jenkins-x/release.yaml
  packs/typescript/.lighthouse/jenkins-x/release.yaml
Labels: size/S

#183 fix: try bigger timeout for previews
  packs/go/preview/helmfile.yaml
Labels: size/XS

#259 fix: go build with jx variables
  packs/go-plugin-multiarch/.lighthouse/jenkins-x/release.yaml
  packs/go-plugin/.lighthouse/jenkins-x/release.yaml
Labels: needs-ok-to-test, size/XS

#271 fix: broken volumes
  packs/javascript-ui-nginx/.lighthouse/jenkins-x/release.yaml
  packs/typescript/.lighthouse/jenkins-x/release.yaml
Labels: size/S

#276 fix: add path flag to build-cargo-install
  tasks/rust/pullrequest.yaml
  tasks/rust/release.yaml
Labels: size/XS

#279 fix: switch to upstream goreleaser image
  tasks/C++/release.yaml
  tasks/D/release.yaml
  tasks/appserver/release.yaml
  tasks/csharp/release.yaml
  tasks/cwp/release.yaml
  tasks/docker-helm/release.yaml
  tasks/docker/release.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
  tasks/go/release.yaml
  tasks/gradle/release.yaml
  tasks/helm/release.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/release.yaml
  tasks/jenkins/release.yaml
  tasks/maven-java11/release.yaml
  tasks/maven-node-ruby/release.yaml
  tasks/maven-quarkus/release.yaml
  tasks/maven/release.yaml
  tasks/ml-python-gpu-service/release.yaml
  tasks/ml-python-service/release.yaml
  tasks/php/release.yaml
  tasks/python/release.yaml
  tasks/ruby/release.yaml
  tasks/rust/release.yaml
  tasks/scala/release.yaml
  tasks/typescript/release.yaml
Labels: size/M

#280 chore: add the env var for tekton-git for goreleaser
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
Labels: size/S

#282 fix: lets commit before releasing binaries
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
Labels: size/S
