Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2022-11, with the labels that each got.

#1287 refactor: update go:1.19.3
  tasks/go-cli/pullrequest.yaml
  tasks/go-cli/release.yaml
  tasks/go-mongodb/pullrequest.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/pullrequest.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/pullrequest.yaml
  tasks/go-plugin/release.yaml
  tasks/go/pullrequest.yaml
  tasks/go/release.yaml
Labels: size/M, approved

#1285 chore: lint task/pack pipelines and helm charts during PR
  .lighthouse/jenkins-x/lint-helm.sh
  .lighthouse/jenkins-x/lint-helm.yaml
  .lighthouse/jenkins-x/lint-pipelines.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: size/L, ok-to-test, approved

#1292 chore: update kaniko to 1.9.1
  tasks/maven-java17/pullrequest.yaml
  tasks/maven-java17/release.yaml
Labels: size/XS, approved

#1293 fix: configure workspace mountPath to avoid permissions issues
  packs/lookml/.lighthouse/jenkins-x/lint.yaml
  tasks/lookml/lint.yaml
Labels: size/S, ok-to-test, approved

#1295 fix: use .docker/config.json path for docker creds
  tasks/build-scan-push/build-scan-push.yaml
  tasks/cosign/cosign.yaml
Labels: size/XS, approved
