Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2022-06, with the labels that each got.

#1128 fix: increase time out for goreleaser
  tasks/go-plugin/release.yaml
Labels: size/XS, approved

#1136 chore: increase timeout for golangci lint to 30m
  tasks/go-plugin/pullrequest.yaml
  tasks/go/pullrequest.yaml
Labels: size/XS

#1140 chore: upgrade golangci lint to 1.46.2
  .gitignore
  tasks/go-plugin-multiarch/pullrequest.yaml
  tasks/go-plugin/pullrequest.yaml
  tasks/go/pullrequest.yaml
Labels: size/S, approved
