Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2022-10, with the labels that each got.

#1247 fix: edit goversion env
  tasks/go-plugin/release.yaml
Labels: size/XS, approved

#1208 Javascript pack fix pr 984
  packs/javascript/.lighthouse/jenkins-x/release.yaml
Labels: size/XS, ok-to-test, approved

#1261 chore: manually bump jx updatebot to 0.3.6
  tasks/flutter/release.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
  tasks/terraform/release.yaml
  tasks/updatebot/release.yaml
Labels: size/S, approved

#1268 refactor: upgrade go version to 1.19.2
  tasks/go-cli/pullrequest.yaml
  tasks/go-cli/release.yaml
  tasks/go-mongodb/pullrequest.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/pullrequest.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/pullrequest.yaml
  tasks/go-plugin/release.yaml
  tasks/go/pullrequest.yaml
  tasks/go/release.yaml
Labels: size/M, approved

#1277 fix: build-make-test for alpine in go-plugin pr
  tasks/go-plugin/pullrequest.yaml
Labels: size/XS, approved

#1280 revert: go back to go non-alpine image
  tasks/go-cli/pullrequest.yaml
  tasks/go-mongodb/pullrequest.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/pullrequest.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/pullrequest.yaml
  tasks/go-plugin/release.yaml
  tasks/go/pullrequest.yaml
  tasks/go/release.yaml
Labels: size/M, approved
