Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2022-04, with the labels that each got.

#915 refactor: upgrade go image to 1.17
  .lighthouse/jenkins-x/tests/go.mod
  .lighthouse/jenkins-x/tests/go.sum
  .lighthouse/jenkins-x/tests/main_test.go
  OWNERS
  tasks/go-cli/pullrequest.yaml
  tasks/go-cli/release.yaml
  tasks/go-mongodb/pullrequest.yaml
  tasks/go-mongodb/release.yaml
  tasks/go-plugin-multiarch/pullrequest.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/pullrequest.yaml
  tasks/go-plugin/release.yaml
  tasks/go/pullrequest.yaml
  tasks/go/release.yaml
Labels: size/XXL, do-not-merge/hold, approved

#956 feat: setup build scan push with trivy
  tasks/build-scan-push/build-scan-push.yaml
Labels: size/M, ok-to-test, approved

#1019 chore: upgrade goreleaser to 1.8.3
  tasks/go-cli/release.yaml
  tasks/go-plugin-multiarch/release.yaml
  tasks/go-plugin/release.yaml
Labels: size/XS, approved

#1022 chore(nodejs): use v14 per v12 EOL
  packs/javascript/Dockerfile
  packs/typescript/Dockerfile
  tasks/javascript-ui-nginx/pullrequest.yaml
  tasks/javascript-ui-nginx/release.yaml
  tasks/javascript/pullrequest.yaml
  tasks/javascript/release.yaml
  tasks/lookml/lint.yaml
  tasks/typescript/pullrequest.yaml
  tasks/typescript/release.yaml
Labels: size/M, lgtm, ok-to-test, approved
