Repository jenkins-x/jx3-pipeline-catalog, pull requests merged in 2025-07, with the labels that each got.

#1666 Update release.yaml
  tasks/javascript-yarn/release.yaml
Labels: ok-to-test, approved

#1667 Update pullrequest.yaml
  tasks/javascript-yarn/pullrequest.yaml
Labels: size/XS, ok-to-test, approved

#1691 fix: tekton is overwriting ~/.gitconfig
  tasks/git-clone/git-clone-env-pr-partial.yaml
  tasks/git-clone/git-clone-env-pr.yaml
  tasks/git-clone/git-clone-pr.yaml
  tasks/git-clone/git-clone.yaml
Labels: size/S, approved
